name: Atualizar Tarifas no Repositorio

on:
  schedule:
    - cron: '0 4 * * *' # Roda todo dia às 04:00 da manhã
  workflow_dispatch: # Permite que você rode manualmente agora para testar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dá permissão para o robô salvar o arquivo no seu projeto

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4

      - name: Executar Scraper
        run: python scraper.py

      - name: Salvar arquivos no GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add tarifas_senior.csv
          # O comando abaixo evita erro se o arquivo não tiver mudado nada
          git commit -m "Atualização automática de tarifas: $(date +'%d/%m/%Y %H:%M')" || echo "Sem mudanças"
          git push
