name: Atualizador de Tarifas

on:
  schedule:
    - cron: '0 3 * * *' # Roda todo dia às 03:00 da manhã
  workflow_dispatch: # Permite que você rode o botão manualmente para testar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite que o robô salve o arquivo no seu git
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependencias
        run: pip install requests beautifulsoup4

      - name: Rodar Script
        run: python scraper.py

      - name: Salvar Mudancas
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dados_tarifas.json
          git commit -m "Tarifas atualizadas automaticamente" || echo "Sem mudanças para salvar"
          git push
