name: Atualizador de Tarifas

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    # Garante que a permissão de escrita seja aplicada a este job específico
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Isso é importante para permitir o push de volta
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependencias
        run: pip install requests beautifulsoup4

      - name: Rodar Script
        run: python scraper.py

      - name: Salvar Mudancas
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Força a adição do arquivo mesmo que ele pareça igual
          git add -f dados_tarifas.json
          
          # O 'date' garante que o commit seja ÚNICO, forçando a atualização
          git commit -m "Atualizacao manual: $(date +'%d-%m-%Y %H:%M:%S')" || echo "Sem mudanças"
          
          # Faz o push para a branch main
          git push origin main


      - name: Enviar para Senior Cloud
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Senior Cloud geralmente exige FTPS (seguro)
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: ./Tarifas_BeneficioFacil/ # Verifique se essa pasta existe lá
          include: |
            *.csv
            *.json
