name: Atualizar Tarifas no Repositorio

on:
  schedule:
    - cron: '0 4 * * *' # Roda todo dia às 04:00 da manhã
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests beautifulsoup4 lxml

      - name: Executar Scraper
        run: python scraper.py

      - name: Salvar no GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add tarifas_senior.txt
          git commit -m "Atualização TXT: $(date +'%d/%m/%Y %H:%M')" || echo "Sem mudanças"
          git push

      - name: Commit e Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add tarifas_senior.txt tarifas_senior.json
          git commit -m "Atualizacao de dados $(date +'%d/%m/%Y')" || echo "Sem mudanças"
          git push
